CREATE TABLE USER(
  USER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  USERNAME VARCHAR(128) NOT NULL UNIQUE,
  PASSWORD VARCHAR(256) NOT NULL
);
/*

CREATE TABLE COURSE(
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(64),
  credits INT
);
ALTER TABLE COURSE ADD FOREIGN KEY (tour_package_code) REFERENCES tour_package(code);

CREATE TABLE Department(
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(64)
);

CREATE TABLE Staff_member(
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  firstName VARCHAR(64),
  lastName VARCHAR(64)
);

CREATE TABLE STUDENT(
  studentId BIGINT AUTO_INCREMENT PRIMARY KEY,
  firstName VARCHAR(64),
  lastName VARCHAR(64),
  fullTime BOOLEAN,
  age INT
);*/